Bga/long due update
zenika-open-source/terraform-aws-cli pull request #59
Opened 2022-08-12 09:51 UTC by bgauduch

- [ ] update all dependencies
- [ ] use local signature files instead of downloading them
- [ ] if possible, add multi-arch support

2022-10-04 08:44 UTC, pyaillet requested changes
Super taf ! 👍 
Une petite remarque sur un truc que je ne suis pas sûr d'avoir bien compris 😅

2022-10-04 08:44 UTC, pyaillet commented on .github/workflows/build-test.yml
> +          export tf_versions=${{ matrix.tf_versions }}
```suggestion
          export TF_VERSION=${{ matrix.tf_versions }}
```

Je ne suis pas sûr de bien comprendre, mais à mon avis ici, on serait bien sur la valorisation de la variable d'environnement vu qu'elle est utilisée en dessous par le `envsubst`, non ?

2022-10-05 13:17 UTC, bgauduch commented on .github/workflows/build-test.yml
> +          export tf_versions=${{ matrix.tf_versions }}
Houuula oui, bien vu 🙏  je corrige ça 👌 

Un grand merci pour ta revue 🤩

2022-10-05 13:20 UTC, pyaillet approved these changes
LGTM! 🚀

2022-10-05 13:22 UTC, pyaillet commented
Erf, did a package version disappear on Debian side?

2022-10-06 13:22 UTC, bgauduch commented
> Erf, did a package version disappear on Debian side?

Yup, which is quite strange ! Must be some sort of security issue 🤔

=> Corrected now with some small additions (1.3.1 release, 1.2.9 support)

2022-10-10 09:29 UTC, pyaillet approved these changes
LGTM!

2022-10-19 13:56 UTC, merged