Devsre 151
zenika-open-source/terraform-aws-cli pull request #86
Opened 2023-11-23 08:07 UTC by thinegan

2023-11-30 19:49 UTC, bgauduch requested changes
Helllo @thinegan 👋 

Thanks a lot for your interest and contribution to this image 🙏 

Nice work, a few questions 😉

2023-12-01 05:47 UTC, thinegan commented
Updated and tested,
note stderr: rosetta error: due to M1 arm64.

`Linting Dockerfile...
Lint Successful!
Building images with AWS_CLI_VERSION=2.14.5 and TERRAFORM_VERSION=1.5.7...
Image successfully builded!
Generating test config with AWS_CLI_VERSION=2.14.5 and TERRAFORM_VERSION=1.5.7...
Test config successfully generated!
Executing container structure test...

==================================
====== Test file: tests.yml ======
==================================
=== RUN: Command Test: Check Git version
--- PASS
duration: 229.766625ms
stdout: git version 2.39.2

=== RUN: Command Test: Check JQ version
--- PASS
duration: 196.53625ms
stdout: jq-1.6

=== RUN: Command Test: Check OpenSSH client version
--- PASS
duration: 223.969791ms
stderr: OpenSSH_9.2p1 Debian-2+deb12u1, OpenSSL 3.0.11 19 Sep 2023

=== RUN: Command Test: Check Terraform CLI version
--- PASS
duration: 1.454684959s
stdout: Terraform v1.5.7
on linux_arm64

Your version of Terraform is out of date! The latest version
is 1.6.5. You can update by downloading from https://www.terraform.io/downloads.html

=== RUN: Command Test: Check AWS CLI version
--- FAIL
duration: 202.926416ms
stderr: rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2

Error: Expected string 'aws-cli/2.14.5' not found in output ''
Error: Test 'Check AWS CLI version' exited with incorrect error code. Expected: 0, Actual: 133
=== RUN: File Existence Test: Check non-root user home
--- PASS
duration: 0s
=== RUN: File Existence Test: Check non-root user rights on /workspace folder
--- PASS
duration: 0s
=== RUN: Metadata Test
--- PASS
duration: 0s

===================================
============= RESULTS =============
===================================
Passes:      7
Failures:    1
Duration:    2.307884041s
Total tests: 8

FAIL`

2023-12-01 10:16 UTC, bgauduch requested changes
Nicely done, thanks again @thinegan 🚀 

A few last tweaks and we should be good to go 👌

2023-12-01 10:16 UTC, bgauduch commented on security/awscli-exe-linux-x86_64-2.14.5.zip.sig
nicely done adding the required sig file for AWS CLI v2.14.5👌 

As version 2.12.5 was removed from supported_versions.json file, you can safely delete the associated sig file 😉

2023-12-01 10:16 UTC, bgauduch commented on security/terraform_1.6.4_SHA256SUMS
This file is not required anymore and can be safely deleted 😉

2023-12-01 10:16 UTC, bgauduch commented on security/terraform_1.6.4_SHA256SUMS.sig
This file is not required anymore and can be safely deleted 😉

2023-12-01 16:34 UTC, bgauduch approved these changes
Awesome 🎉

2023-12-01 16:34 UTC, merged